- src/MimeCategory.cpp
Qt4 didn't yet have a QStringList::sort(CaseSensitivity&)
member.  This is just for visual feedback, so ignore it, and
sort with defaults.
Signed-off-by: Michael Matz <matz@suse.de>
> [qt4] Don't use extendend QStringList::sort

- doc/doc.pro
- scripts/scripts.pro
The Qt4 qmake doesn't like an really empty TARGET specification
in *.pro.  It replaces it by the name of the containing subdir,
hence a make in e.g. 'scripts/' tries to make the executable
'scripts', of course without defined SOURCES that fails.
Trick qmake by making it look like TARGET is not empty, when
in reality it will be by using a not-defined make variable.
Signed-off-by: Michael Matz <matz@suse.de>
> [qt4] Adjust empty TARGET in *.pro

- src/DirTreeView.cpp
closeAllExcept() may get called after currentChanged(), make sure
current item is visible after collapsing entries
> DirTreeView::closeAllExcept(): add scrollTo()

- src/Logger.cpp
Failed because qt4 uses char, not QString for the message. I've also added the qt4 message for being unable to connect to the display.
> Fix compilation failure with qt4 after bf8655

- src/DirReadJob.cpp
- src/DirTreeCache.cpp
- src/Exception.cpp
- src/Logger.cpp
- src/Trash.cpp
All strings read from glibc are in locale encoding, so fromUtf8() must be used before using them.
before:
`
2017-06-01 18:55:18.101 [4713] <WARNING> DirReadJob.cpp:281 startReading():  lstat(/tmp/aaa/krowa/dir2/sdsad) failed: Brak dostÄpu
`
after patch:
`
2017-06-01 19:05:18.558 [5768] <WARNING> DirReadJob.cpp:281 startReading():  lstat(/tmp/aaa/krowa/dir2/sdsad) failed: Brak dostępu
`
> fix UTF-8 in error messages

- doc/QDirStat-for-Servers.md
Previously it linked to the HTML page not the actual file.
> Fix qdirstat-cache-writer raw link in docs

- src/PkgManager.cpp
- src/Qt4Compat.h
use the QProcess compat wrapper in the new PkgManager.  Also
Qt::escape is only declared in <qtextdocument.h>, it's not
included with just <Qt> :-/
Signed-off-by: Michael Matz <matz@suse.de>
> [qt4] Adjustments for recent changes

- src/DataColumns.h
Minor fix: include directive for <QStringList> added to DataColumns.h. Some combination of Qt and gcc versions don't build QDirStat without it.
> Added missing headers for Qt4 support

- scripts/qdirstat-cache-writer
Rather than writing the entire uncompressed cache file,
then compressing in a 2nd pass (which consumes *much* more
space, and is slower due to all the I/O)...
Instead write the output to a pipeline that compresses via external
gzip during the first (and only) pass.
This preserves the "no addititional dependencies" theme in the current
perl script, doing this via the same external gzip program used by
the former 2-pass approach.  Presumably because the headless server
running this script may be a very minimal embedded linux, *BSD, etc.
Single process sol'n can use ">:gzip" from the perl IO gzip layer
(packaged as libperlio-gzip-perl in debian/ubuntu), but not sure
if this is available on all servers you want to support.
2nd bundled commit ensures that (whether doing compression or not), …
> When compression is requested, do it in one pass

- qdirstat.pro
According to bug https://github.com/shundhammer/qdirstat/issues/65 by removing all folders except src, the application is able to compile and run.
> Compiles under macos

- src/MimeCategorizer.cpp
These are some common (and some less common) archive and audio formats that I suggest adding to the defaults.
Opus, zst, and xz are very common. fsa (generated by fsarchiver) and tar.lzo are much less common, but still valid archives.
> Add more archive and audio file types to categories

- README.md
- doc/Debugging-Tips.md
- doc/DevHistory.md
- src/DirTreeModel.cpp
- src/DirTreeModel.h
- src/FileInfo.cpp
- src/MainWindow.h
- src/SysUtil.h
Found via `codespell -q 3 -L ro,te`
> Fix various typos

- doc/QDirStat-for-Servers.md
Tried installing URI::Escape on a new GCP VM, got a bunch of errors that I managed to track down to make not being installed for whatever reason. Fixed by installing `build-essential` and re-running `cpan URI::Escape`.
EDIT: I'm not sure about the language used for the note, feel free to make it better.
> Add note for installing make to install URI::Escape to use qdirstat-cache-writer

- README.md
Update link to the page of the Fedora pre-built QDirStat package (old link was a 404)
> Update link to Fedora package page

- src/MimeCategorizer.cpp
- src/MimeCategorizer.h
- src/MimeCategoryConfigPage.cpp
- src/MimeCategoryConfigPage.h
- src/TreemapView.cpp
- src/TreemapView.h
This code in treemapView was marked TO DO, so I did.  There are now two extra categories:
- one for executable files that don't match anything else;
-  one for all symlinks regardless of the name
The two categories cannot be deleted from the config dialog and will be recreated if they are lost from the config file.  The colours can be configured.  Patterns can be added for the executable category, but not for the symlink one.
> Make the executable and symlink mime type colours configurable

- src/MimeCategoryConfigPage.cpp
- src/MimeCategoryConfigPage.h
Override the ListEditor updateActions() so that the remove button remains disabled for the symlink and executable categories when they become the current item after a category has been deleted.
Disable everything except the add button when there are no categories (shouldn't happen but was happening in some cases before this fix).  Also set the mini-treemap to the default fixed colour when the last category is removed, and reset the name, colour and patterns in the dialog.
See issue #238.
> Mime categorizer config fixes

- src/SystemFileChecker.h
Found while compiling version 1.9.  This fixes the following compilation error (at least under clang), caused by missing include for `uid_t`.
```
SystemFileChecker.cpp:43:25: error: out-of-line definition of 'isSystemUid' does not match any declaration in 'QDirStat::SystemFileChecker'
bool SystemFileChecker::isSystemUid( uid_t uid )
> Added missing include for `uid_t` type.

- src/DirReadJob.cpp
Fixes:
--- .obj/DirReadJob.o ---
DirReadJob.cpp: In member function 'virtual void QDirStat::LocalDirReadJob::startReading()':
DirReadJob.cpp:225:37: error: 'X_OK' was not declared in this scope; did you mean 'Z_OK'?
225 |     if ( access( _dirName.toUtf8(), X_OK | R_OK ) != 0 )
|                                     ^~~~
|                                     Z_OK
DirReadJob.cpp:225:44: error: 'R_OK' was not declared in this scope; did you mean 'Z_OK'?
225 |     if ( access( _dirName.toUtf8(), X_OK | R_OK ) != 0 )
|                                            ^~~~
|                                            Z_OK
DirReadJob.cpp:225:10: error: 'access' was not declared in this scope
225 |     if ( access( _dirName.toUtf8(), X_OK | R_OK ) != 0 )
|          ^~~~~~
> Add missing header for access().

- src/SelectionModel.cpp
During an AssumeDeleted cleanup, SelectionModel checks to see if the current item has been deleted.  Unfortunately, if the current item has been deleted, then the pointer to it is already invalid.  Check the pointer first; if it is already null then we don't need to set it to null.  Is the check ever meaningful?  Can the current item ever not be in the subtree that is being cleaned up?
> Fix use of null pointer during AssumeDeleted cleanup

- src/DirReadJob.cpp
The DirReadQueue zero-second timer is not stopped when a read is aborted, which leads to 100% cpu usage and lockup of some gui actions.  The timer is only stopped when a job completes normally and at that point the queue is empty.
The timer could just be stopped in clear(), but to catch any other cases now or in the future, stop the timer whenever the queue is empty at the time that the timer fires.
> Fix timer not stopped on abort

- src/MimeCategorizer.cpp
Added extensions that were listed in Other on v1.9 and a few others observed as missing while reviewing the categories during this edit. I have not compile tested this yet.
> Add extensions to MimeCategorizer.cpp

- src/io.github.shundhammer.qdirstat.metainfo.xml
- src/src.pro
This is required for https://github.com/flathub/flathub/pull/6172 but not @flatpak exclusive. Other distribution channels will also use it to populate the app storefronts. See https://www.freedesktop.org/software/appstream/docs/ for details.
> Add AppStream metadata

- scripts/qdirstat-cache-writer
CEPHFS  can report the recursive file size of directories when CEPH is mounted with the `rbytes` option. This pull request adds a ` -i` option. When enabled, this option sets the directory size to 0. This option is a workaround/fix #281
> [feat] add -i option to qdirstat-cache-writer
